### PR TITLE
Finnish weekdays + Build and publish latest changes

### PR DESCRIPTION
**Pull request by mduqueoviedo**
It seems the latest additions to the library had not being published, hence not available publicly in npm. Now everything should be ok!

### CODE REVIEW

**Comment by mduqueoviedo** [comment]
I also added a fix into the Finnish weekdays, they were starting by Monday! 😅 🇫🇮

**Comment by bradymholt** [comment]
Thanks @mduqueoviedo .  I had a bug with my new release script that was causing new assets to not be packaged up. I fixed that here: https://github.com/bradymholt/cRonstrue/pull/144.  Would you mind removing the build assets and changes to package.json here and just making changes to that Finnish i18n?  Then, I can merge this in.

**Comment by mduqueoviedo** [comment]
Fiuuu! That should be all! Thanks for the hard work @bradymholt :)

**Comment by bradymholt** [comment]
Thanks!

**Pull request merged**
