### PR TITLE
Feature/separate locales (Closes #223)

### LINKED ISSUE #223: [Build request] Option to select which locales to include
The locales files weigh over 100KB. An option to select which locales to include - would be great.

### PR DESCRIPTION
**Pull request by danielgindi**

### CODE REVIEW

**Comment by bradymholt** [comment]
Hi @danielgindi - this is great! I've been really hoping someone would make this contribution.  I am tied up through the end of this week but have a reminder to take a look here early next week.

**Comment by bradymholt** [comment]
@danielgindi - Thanks again!  A few notes here:

- I ran the tests here and am seeing some failures and I also see the same failures locally. Do you know what is going on there?
- Would you mind updating the README here, related to i18n?
- How do you imagine these locales will be imported? With something like `require('cronstrue/dist/i18n/locales/fr')`?  Should we make use of `exports` in package.json or copy entry files to root so that consumers can do this: `require('cronstrue/fr')`?
- When testing locally, I'm having trouble requiring with CommonJS.  The following:
    ```
    var cronstrue = require('cronstrue/dist/i18n/locales/fr');
    console.log(cronstrue.toString("*/5 * * * *"));
    ```
     outputs:
     ```
     [object Module]
     ```

**Comment by danielgindi** [comment]
> * I ran the tests here and am seeing some failures and I also see the same failures locally. Do you know what is going on there?

I just fixed it and pushed. Lot's of typescript issues. Nothing functional of course as I did not originally touch the source code.

> * Would you mind updating the README here, related to i18n?

Just did :-)

> * How do you imagine these locales will be imported? With something like `require('cronstrue/dist/i18n/locales/fr')`?  Should we make use of `exports` in package.json or copy entry files to root so that consumers can do this: `require('cronstrue/fr')`?

It's in the readme now... 
Anyway I think we can generate the i18n dist files to `/locales` so it will be easier to reference.

> * When testing locally, I'm having trouble requiring with CommonJS. 
You should first require the main `cronstrue` (without locales), and then require the individual locales you want.  Like this:

```js
var cronstrue = require('cronstrue');
require('cronstrue/dist/i18n/locales/fr');
console.log(cronstrue.toString("*/5 * * * *"));
```

**Comment by danielgindi** [comment]
@bradymholt gentle ping :)

**Comment by bradymholt** [comment]
Thanks!

**Comment by bradymholt** [comment]
I'm making a few tweaks to these changes in https://github.com/bradymholt/cRonstrue/pull/230 and once I'm done with that I will merge and publish.

**Comment by bradymholt** [comment]
Released as part of [2.1.0](https://www.npmjs.com/package/cronstrue/v/2.1.0).

**Pull request merged**
