### PR TITLE
Can you help me add translate vietnamese ^^

### PR DESCRIPTION
**Pull request by rikkapro0128**

### CODE REVIEW

**Comment by bradymholt** [comment]
Thanks!  Can you also update README.md to add this one to [the list](https://github.com/bradymholt/cRonstrue#supported-locales)?

**Comment by rikkapro0128** [comment]
> Thanks! Can you also update README.md to add this one to [the list](https://github.com/bradymholt/cRonstrue#supported-locales)?

ok i will

**Comment by bradymholt** [comment]
Thanks!

**Comment by bradymholt** [comment]
Released in v2.28.0

**Pull request merged**
